### ISSUE TITLE
installing from TerriaJS repo instead of personal repo

### ISSUE THREAD

**Issue by zdefne-usgs** [rsignell-usgs/docker-terria-usgs#6]
After adding the following lines to the Dockerfile  it is no longer required to clone from a separate github repo. 
```
COPY ./files/feedback.js /usr/local/app/TerriaMap/node_modules/terriajs-server/lib/controllers/feedback.js
COPY ./files/index.js /usr/local/app/TerriaMap/index.js
COPY ./files/UserInterface.jsx /usr/local/app/TerriaMap/lib/Views/UserInterface.jsx
COPY ./images/ /usr/local/app/TerriaMap/wwwroot/build/
```
Also the following folders need to be copied in the same folder with the Dockerfile prior to buiding the image. 
 - /files
Files required for customization beyond what can be implemented with the json files. e.g. `'feedback.js`, `index.js` and `UserInterface.jsx`.
 - /images
Thumbnail images for basemaps

However, the thumbnail images for the basemaps  do not change, which is very odd. Because with this approach we are actually replacing the images in the cloned repo prior to building the image...

**Comment by zdefne-usgs** [comment]
The way the thumbnails work is a bit strange to me. I had to replace the images under the build folder to get them to work.  For the modified Dockerfile see PR #7 and #8

**Comment by zdefne-usgs** [comment]
Agreed to follow up with TerriaJS developers regarding the way the thumbnail images work.

**Comment by zdefne-usgs** [comment]
@kring [Here](https://github.com/rsignell-usgs/docker-terria-usgs) is how we have created a plain TerriaJS to be used for USGS applications. One request was to avoid installing from a personal branch of TerriJS. So we clone from the original TerriJS repo, and apply the changes to the `.js` and `.jsx` files  by copying the modified versions in the docker container during installation (link to Dockerfile [here](https://github.com/rsignell-usgs/docker-terria-usgs/blob/master/Dockerfile)). 

So a couple of quick questions:
 - Does this procedure make sense or is there a better way to do it? 
 - To change the thumbnails for basemaps (AU to USA) we had to replace the images in the build folder, rather than the wwwroot/images folder. So for example instead of `bing-aerial.png` it is `[alphanumeric characters].png`. So instead of using the links to the original thumbnail pngs, Terria is creating copies with unique names during building . Is this how the installation supposed to work? 
Thanks!

**Comment by kring** [comment]
@zdefne-usgs I would say that the TerriaMap repo is meant for forking, and you're probably just making things harder than necessary by trying to avoid this. Specifically, what happens if UserInterface.jsx or any of the other files you've changed are modified? Your current process would silently replace the new version with your modified copy of the old one. That could lead to build failures or missing features.

On the other hand, if you use Git to manage your changes (by forking the TerriaMap repo), Git's normal merging process will silently merge your changes with any new upstream changes in most cases, and alert you when there's a conflict. 

If you're concerned about your fork getting out of date, you could potentially do the git merge inside the Dockerfile.  E.g.:

```
git remote add upstream git@github.com:TerriaJS/TerriaMap.git
git fetch upstream
git merge upstream/master
```

In effect, your Dockerfile as written right now is doing a merge on every build, but it's doing so in a pretty blunt "always accept my version of the file" sort of way.

Regarding the basemap thumbnails, the weird naming comes from our Webpack build process. The idea is that built resources have unique names based on a hash of their content, so you can (in theory) configure your web server to cache files forever. If the content of the file changes, the name will change too. To avoid the strange names (which, again, will change whenever the content changes), you can copy your files into `node_modules/terriajs/wwwroot/images` _before_ doing a build. Another option, which is better IMO, especially when paired with my advice above, is to override the thumbnails in TerriaMap. Your TerriaMap index.js is presumably calling `createGlobalBaseMapOptions`. Rather than calling the TerriaJS version, copy the entire source file into your TerriaMap's `lib` directory, change the `require` statement in index.js to require in your version rather than the TerriaJS version, and then modify it as you see fit (e.g. add/remove base map options, specify new thumbnail images). Or, if you don't want to fork `createGlobalBaseMapOptions` (maybe because you want to automatically pick up new base maps from upstream), you can make your index.js call the TerriaJS version of that function, and then replace the `image` property in each element of the returned array.

I hope that makes some sense. Let me know if any part of it is unclear.

**Comment by rsignell-usgs** [comment]
@kring, this is great.   Thanks so much for steering us in the right direction!

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , let's return to the concept of our own fork/branch, and rely on git merge to keep up with developments.

**Comment by zdefne-usgs** [comment]
We are now providing two different options for deployment: Personal repo or the original TerriaJS repo.

**Comment by zdefne-usgs** [comment]
@kring 
Method 1
> To avoid the strange names (which, again, will change whenever the content changes), you can copy your files into node_modules/terriajs/wwwroot/images before doing a build. 

This is similar to what I am already doing. This can be done in the Dockerfile after cloning from the source repo, correct? And it can be implemented with additional Docker commands to copy the files into the image, correct? 

Method 2
>Another option, which is better IMO, especially when paired with my advice above, is to override the thumbnails in TerriaMap. Your TerriaMap index.js is presumably calling createGlobalBaseMapOptions. Rather than calling the TerriaJS version, copy the entire source file into your TerriaMap's lib directory, change the require statement in index.js to require in your version rather than the TerriaJS version, and then modify it as you see fit (e.g. add/remove base map options, specify new thumbnail images). 

This is a good idea, because this way we can have everything stored in our TerriaMap repo and no additional tinkering during building. Unfortunately the require statements are like layers of onion if I were to replace all of them in the `createGlobalBaseMapOptions`. They require additional functions from TerriaJS. I will try to replace the ones that are used only for pushing the images and leave the rest as they are. 

>Or, if you don't want to fork createGlobalBaseMapOptions (maybe because you want to automatically pick up new base maps from upstream), you can make your index.js call the TerriaJS version of that function, and then replace the image property in each element of the returned array.

And this is what you have already suggested here, I think (it is clearer to me after I looked at the code).
Will give it a shot and report back soon. Cheers!

**Comment by zdefne-usgs** [comment]
Looks like it worked. But the thumbnails for Bing maps are not updated. Is it because the are coming through Ion? Hmm...

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , where did you deploy this?

**Comment by zdefne-usgs** [comment]
https://gamone.whoi.edu/terria_usgs2/

**Comment by rsignell-usgs** [comment]
I see what you mean!  
![2018-11-16_14-46-04](https://user-images.githubusercontent.com/1872600/48643783-a369c780-e9ae-11e8-96d5-be6ab0a075bf.png)

**Comment by zdefne-usgs** [comment]
@kring 
these [lines ](https://github.com/USGS-CMG/TerriaMap/blob/ddf1b0cb88feaf83305ca89b0f5c1ef6f51348f0/lib/ViewModels/createBingBaseMapOptions.js#L34
)
`                bingMapsAerial = new IonImageryCatalogItem(terria);
``
                 bingMapsAerial.ionAssetId = IonWorldImageryStyle.AERIAL;
`
seems to be not affected by this [line](https://github.com/USGS-CMG/TerriaMap/blob/ddf1b0cb88feaf83305ca89b0f5c1ef6f51348f0/lib/ViewModels/createBingBaseMapOptions.js#L56)
`    result.push(new BaseMapViewModel({         
image: require('../../wwwroot/images/bing-aerial.png'),`

**Comment by kring** [comment]
The code you linked looks fine. I think the problem is that your `createGlobalBaseMapOptions` is requiring the TerriaJS version of `createBingBaseMapOptions` instead of your own:
https://github.com/USGS-CMG/TerriaMap/blob/ddf1b0cb88feaf83305ca89b0f5c1ef6f51348f0/lib/ViewModels/createGlobalBaseMapOptions.js#L4

**Comment by kring** [comment]
i.e. this:

```
var createBingBaseMapOptions = require('terriajs/lib/ViewModels/createBingBaseMapOptions');
```

should change to this:

```
var createBingBaseMapOptions = require('./createBingBaseMapOptions');
```

**Comment by zdefne-usgs** [comment]
Got it. Thank you, Kevin!
